fappa/src/Entity/Annonce.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\AnnonceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=AnnonceRepository::class)
 */
class Annonce
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_postale;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0, nullable=true)
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_published;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_create;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_update;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_info;

    /**
     * @ORM\ManyToMany(targetEntity=Categorie::class, inversedBy="annonces")
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="annonce", orphanRemoval=true)
     */
    private $commentaires;

    public function __construct()
    {
        $this->date_create = new \DateTime();
        $this->categorie = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostale(): ?string
    {
        return $this->code_postale;
    }

    public function setCodePostale(string $code_postale): self
    {
        $this->code_postale = $code_postale;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(?string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(bool $is_published): self
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(\DateTimeInterface $date_create): self
    {
        $this->date_create = $date_create;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(\DateTimeInterface $date_update): self
    {
        $this->date_update = $date_update;

        return $this;
    }

    public function getUserInfo(): ?Users
    {
        return $this->user_info;
    }

    public function setUserInfo(?Users $user_info): self
    {
        $this->user_info = $user_info;

        return $this;
    }

    /**
     * @return Collection|Categorie[]
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(Categorie $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
        }

        return $this;
    }

    public function removeCategorie(Categorie $categorie): self
    {
        $this->categorie->removeElement($categorie);

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setAnnonce($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getAnnonce() === $this) {
                $commentaire->setAnnonce(null);
            }
        }

        return $this;
    }
}

fappa/src/Controller/AnnonceController.php
<?php

namespace App\Controller;

use App\Repository\AnnonceRepository;
use App\Entity\Annonce;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AnnonceController extends AbstractController
{
    /**
     * @Route("/annonces", name="annonces")
     */
    public function index(AnnonceRepository $annoneRepo, PaginatorInterface $paginator, Request $request): Response
    {
        $data = $annoneRepo->findAll();

        $annonces = $paginator->paginate(
            $data,
            $request->query->getInt('page', 1),
            6
        );

        return $this->render('annonces/index.html.twig', [
            'annonces' => $annonces,
        ]);
    }

    /**
     * @Route("/annonce/{slug}", name="annonce_details")
     */
    public function details(Annonce $annonce): Response
    {
        return $this->render('annonces/details.html.twig', [
            'annonce' => $annonce
        ]);
    }
}

fappa/templates/annonces/bloc_header.html.twig
{% block body %}
<section class="section-header bg-primary text-white pb-10 pb-sm-8 pb-lg-11">
   <div class="container">
      <div class="row justify-content-center">
         <div class="col-12 col-md-8 text-center">
            <h1 class="display-2 mb-4">Our Blog</h1>
            <p class="lead">We help you get better at SEO and marketing: detailed tutorials, case studies and opinion pieces from marketing practitioners and industry experts alike</p>
         </div>
      </div>
   </div>
</section>
{% endblock %}

fappa/templates/annonces/card_list.html.twig
{% block body %}
<section class="section section-lg line-bottom-light">
   <div class="container mt-n10 mt-lg-n12 z-2">
      <div class="row">
         <div class="col-lg-12 mb-5">
            <div class="card shadow bg-white border-gray-300 flex-lg-row align-items-center g-0 p-4">
               <a href="./blog-post.html" class="col-12 col-lg-6"><img src="https://source.unsplash.com/random/530x350" alt="themesberg office" class="card-img-top rounded"></a>
               <div class="card-body d-flex flex-column justify-content-between col-auto py-4 p-0 p-lg-3 p-xl-5">
                  <a href="./blog-post.html">
                     <h2>Designing a dashboard that increases business value</h2>
                  </a>
                  <p>Today we are overwhelmed by content, and inspiration can strike anywhere. The point is to collect it and share it in a structured way to inspire your team, client, and users. In this article, I will show you how to design a dashboard.</p>
                  <div class="d-flex align-items-center mt-3">
                     <img class="avatar avatar-sm rounded-circle" src="../../assets/img/team/profile-picture-1.jpg" alt="Richard avatar">
                     <h3 class="h6 small ms-2 mb-0">Richard Thomas</h3>
                     <span class="h6 text-muted small fw-normal mb-0 ms-auto"><time datetime="2019-04-25">21 February, 2019</time></span>
                  </div>
               </div>
            </div>
         </div>
         {% for annonce in annonces %}
         <div class="col-12 col-md-6 col-lg-4 mb-4 mb-lg-5">
            <div class="card shadow bg-white border-gray-300 p-4 rounded">
               <a href="{{ path('annonce_details', { 'slug': annonce.slug }) }}"><img src="{{ annonce.image }}" class="card-img-top rounded" alt="our desk"></a>
               <div class="card-body p-0 pt-4">
                  <a href="./blog-post.html" class="h4">{{ annonce.titre }}</a>
                  <div class="d-flex align-items-center my-3">
                     <img class="avatar avatar-sm rounded-circle" src="../../assets/img/team/profile-picture-2.jpg" alt="Neil avatar">
                     <h3 class="h6 small ms-2 mb-0">{{ annonce.userInfo.prenom }} {{ annonce.userInfo.nom }}</h3>
                  </div>
                  <p class="mb-0">{{ annonce.description|u.truncate(100, '...', false) }}</p>
               </div>
            </div>
         </div>
         {% endfor %}
         <div class="col-12">
            <div class="d-flex justify-content-center">
               <nav aria-label="Page navigation example">
                  <ul class="pagination">
                     {% do annonces.setPageRange(2) %}
                     {{ knp_pagination_render(annonces, 'annonces/pagination.html.twig') }}
                  </ul>
               </nav>
            </div>
         </div>
      </div>
   </div>
</section>
{% endblock %}

fappa/templates/annonces/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail - {{ annonce.titre }}{% endblock %}

{% block body %}
<!DOCTYPE html>
<html lang="en">

{{ include ('utils/_script.html.twig') }}
{{ include ('utils/_header.html.twig') }}

<body>

<main>
   <section class="section-header pb-5 pb-sm-7 bg-primary text-white">
      <div class="container">
         <div class="row justify-content-center">
            <div class="col-12 col-lg-10 text-center">
                {% for categorie in annonce.categorie %}            
                   <div class="mb-4"> <a class="badge bg-warning text-uppercase px-3">{{ categorie.nom }}</a></div>
                {% endfor %}
               <h1 class="display-3 mb-4 px-lg-5">{{ annonce.titre |upper }}</h1>
               <h3 class="display-3 mb-4 px-lg-5">{{ annonce.prix }} € </h3>
               <div class="post-meta"><span class="fw-bold me-3">Créé par {{ annonce.userInfo.prenom }} {{ annonce.userInfo.nom }}</span> <span class="post-date me-3">{{ annonce.dateCreate | format_datetime(locale='fr')}}</span> </div>
            </div>
         </div>
      </div>
   </section>
   <div class="section section-sm bg-white pt-5 pt-lg-6 text-black">
      <article class="container">
         <div class="row justify-content-center">
            <div class="col-12 col-lg-8">
               <p><img class="rounded" src="{{ annonce.image }}" alt="Themesberg office"></p>
               <h2>Description</h2>
               <p>{{ annonce.description }}</p>
               <h4>{{ annonce.adresse }}, {{ annonce.ville }} {{ annonce.codePostale }}</h4>
            </div>
         </div>
         <div class="row justify-content-sm-center align-items-center py-3 mt-3">
            <div class="col-12 col-lg-8">
               <div class="row">
                  <div class="col-9 col-md-6">
                     <h6 class="fw-bolder d-inline mb-0 me-3">Share:</h6>
                     <button class="btn btn-sm me-2 btn-icon-only btn-pill btn-twitter d-inline text-white" aria-label="twitter social link"><span class="fab fa-twitter"></span></button> <button class="btn btn-sm me-2 btn-icon-only btn-pill btn-facebook d-inline" aria-label="facebook social link"><span class="fab fa-facebook-f"></span></button> <button class="btn btn-sm btn-icon-only btn-pill bg-orange d-inline text-white" aria-label="reddit social link"><span class="fab fa-reddit-alien"></span></button>
                  </div>
                  <div class="col-3 col-md-6 text-right"><span class="far fa-bookmark text-primary" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-original-title="Bookmark story" data-bs-original-title="Bookmark story" aria-label="Bookmark story"></span></div>
               </div>
            </div>
         </div>
      </article>
   </div>
   <div class="section section-md bg-white text-black pt-0 line-bottom-light">
      <div class="container">
         <div class="row justify-content-center">
            <div class="col-12 col-lg-8">
               <div>
                  <label class="h5 mb-4" for="exampleFormControlTextarea1"><span class="badge badge-md bg-primary text-uppercase me-2">23</span> Comments</label> 
                  <textarea class="form-control border border-gray-300-gray" id="exampleFormControlTextarea1" placeholder="Add your comment" rows="6" data-bind-characters-target="#charactersRemaining" maxlength="1000"></textarea>
                  <div class="d-flex justify-content-between mt-3"><small class="fw-light text-dark"><span id="charactersRemaining">1000</span> characters remaining</small> <button class="btn btn-primary animate-up-2">Send</button></div>
               </div>
            </div>
         </div>
      </div>
   </div>
</main>

</body>

{{ include ('utils/_footer.html.twig') }}

</html>
{% endblock %}

fappa/templates/annonces/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces{% endblock %}

{% block body %}
<!DOCTYPE html>
<html lang="en">

{{ include ('utils/_script.html.twig') }}
{{ include ('utils/_header.html.twig') }}

<body>

   {{ include ('annonces/bloc_header.html.twig') }}
   {{ include ('annonces/card_list.html.twig') }}

</body>

{{ include ('utils/_footer.html.twig') }}

</html>
{% endblock %}

fappa/templates/annonces/pagination.html.twig
{% if pageCount > 1 %}
    <nav>
        {% set classAlign = (align is not defined) ? '' : align=='center' ? ' justify-content-center' : (align=='right' ? ' justify-content-end' : '') %}
        {% set classSize = (size is not defined) ? '' : size=='large' ? ' pagination-lg' : (size=='small' ? ' pagination-sm' : '') %}
        <ul class="pagination{{ classAlign }}{{ classSize }}">

            {% if previous is defined %}
                <li class="page-item">
                    <a class="page-link" rel="prev" href="{{ path(route, query|merge({(pageParameterName): previous})) }}">&laquo;&nbsp;{{ 'label_previous'|trans({}, 'KnpPaginatorBundle') }}</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo;&nbsp;{{ 'label_previous'|trans({}, 'KnpPaginatorBundle') }}</span>
                </li>
            {% endif %}

            {% if startPage > 1 %}
                <li class="page-item">
                    <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): 1})) }}">1</a>
                </li>
                {% if startPage == 3 %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): 2})) }}">2</a>
                    </li>
                {% elseif startPage != 2 %}
                    <li class="page-item disabled">
                        <span class="page-link">&hellip;</span>
                    </li>
                {% endif %}
            {% endif %}

            {% for page in pagesInRange %}
                {% if page != current %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): page})) }}">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="page-item active">
                        <span class="page-link">{{ page }}</span>
                    </li>
                {% endif %}

            {% endfor %}

            {% if pageCount > endPage %}
                {% if pageCount > (endPage + 1) %}
                    {% if pageCount > (endPage + 2) %}
                        <li class="page-item disabled">
                            <span class="page-link">&hellip;</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): (pageCount - 1)})) }}">{{ pageCount -1 }}</a>
                        </li>
                    {% endif %}
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): pageCount})) }}">{{ pageCount }}</a>
                </li>
            {% endif %}

            {% if next is defined %}
                <li class="page-item">
                    <a class="page-link" rel="next" href="{{ path(route, query|merge({(pageParameterName): next})) }}">{{ 'label_next'|trans({}, 'KnpPaginatorBundle') }}&nbsp;&raquo;</a>
                </li>
            {% else %}
                <li  class="page-item disabled">
                    <span class="page-link">{{ 'label_next'|trans({}, 'KnpPaginatorBundle') }}&nbsp;&raquo;</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}